class DefineException(Exception):
    pass

class LoadException(Exception):
    pass